import type { CSSProperties } from "react";

import type { BackgroundPreset, ThemePreset } from "./types";

type ThemeStyle = CSSProperties & Record<`--${string}`, string>;

function rgbaTriplet(triplet: string, alpha: string) {
  return `rgba(${triplet.replaceAll(" ", ", ")}, ${alpha})`;
}

export function createThemeVars(theme: ThemePreset, background: BackgroundPreset): ThemeStyle {
  const { tokens, surfaceStyles } = theme;

  return {
    "--color-canvas": tokens.colors.canvas,
    "--color-surface": tokens.colors.surface,
    "--color-surface-strong": tokens.colors.surfaceStrong,
    "--color-surface-glass": tokens.colors.surfaceGlass,
    "--color-line": tokens.colors.line,
    "--color-line-strong": tokens.colors.lineStrong,
    "--color-text": tokens.colors.text,
    "--color-text-muted": tokens.colors.textMuted,
    "--color-primary": tokens.colors.primary,
    "--color-primary-strong": tokens.colors.primaryStrong,
    "--color-accent": tokens.colors.accent,
    "--color-accent-soft": tokens.colors.accentSoft,
    "--color-success": tokens.colors.success,
    "--color-warning": tokens.colors.warning,
    "--color-danger": tokens.colors.danger,
    "--ake-blue": tokens.akePalette.blue,
    "--ake-blue-deep": tokens.akePalette.blueDeep,
    "--ake-indigo": tokens.akePalette.indigo,
    "--ake-orange": tokens.akePalette.orange,
    "--ake-orange-deep": tokens.akePalette.orangeDeep,
    "--ake-cream": tokens.akePalette.cream,
    "--ake-ink": tokens.akePalette.ink,
    "--ake-mist": tokens.akePalette.mist,
    "--font-brand": tokens.typography.brand,
    "--font-body": tokens.typography.body,
    "--font-mono": tokens.typography.mono,
    "--font-size-hero": tokens.typography.hero,
    "--font-size-title": tokens.typography.title,
    "--font-size-body": tokens.typography.bodySize,
    "--font-size-caption": tokens.typography.caption,
    "--space-section": tokens.spacing.section,
    "--space-block": tokens.spacing.block,
    "--space-gap": tokens.spacing.gap,
    "--radius-shell": tokens.radius.shell,
    "--radius-panel": tokens.radius.panel,
    "--radius-control": tokens.radius.control,
    "--radius-chip": tokens.radius.chip,
    "--radius-badge": tokens.radius.badge,
    "--radius-media": tokens.radius.media,
    "--radius-pill": tokens.radius.pill,
    "--blur-soft": tokens.blur.soft,
    "--blur-strong": tokens.blur.strong,
    "--shadow-soft": tokens.shadow.soft,
    "--shadow-floating": tokens.shadow.floating,
    "--shadow-inset": tokens.shadow.inset,
    "--opacity-copy-soft": tokens.opacity.copySoft,
    "--text-muted-strong": rgbaTriplet(tokens.colors.textMuted, tokens.opacity.copySoft),
    "--text-muted-soft": rgbaTriplet(tokens.colors.textMuted, "0.72"),
    "--text-muted-faint": rgbaTriplet(tokens.colors.textMuted, "0.84"),
    "--text-primary-strong": rgbaTriplet(tokens.colors.text, tokens.opacity.copyStrong),
    "--stroke-soft": rgbaTriplet(tokens.colors.line, tokens.opacity.lineSoft),
    "--stroke-strong": rgbaTriplet(tokens.colors.lineStrong, tokens.opacity.lineSoft),
    "--stroke-accent": rgbaTriplet(tokens.akePalette.orange, tokens.opacity.tintStrong),
    "--stroke-success": rgbaTriplet(tokens.colors.success, tokens.opacity.tintStrong),
    "--stroke-focus": rgbaTriplet(tokens.akePalette.blueDeep, tokens.opacity.tintStrong),
    "--stroke-dashed": rgbaTriplet(tokens.colors.lineStrong, tokens.opacity.tintSoft),
    "--glass-highlight": `linear-gradient(180deg, ${rgbaTriplet(tokens.colors.surfaceGlass, tokens.opacity.highlight)}, transparent 26%)`,
    "--glass-panel-bg": `linear-gradient(180deg, ${rgbaTriplet(tokens.colors.surfaceGlass, tokens.opacity.glassStrong)}, ${rgbaTriplet(tokens.colors.surface, tokens.opacity.glassSoft)}), ${surfaceStyles.rainWash}`,
    "--glass-panel-strong-bg": `linear-gradient(180deg, ${rgbaTriplet(tokens.colors.surfaceGlass, "0.88")}, ${rgbaTriplet(tokens.colors.surfaceStrong, "0.86")}), ${surfaceStyles.rainWash}`,
    "--glass-panel-tinted-bg": `radial-gradient(circle at top right, ${rgbaTriplet(tokens.akePalette.orange, tokens.opacity.tintSoft)}, transparent 24%), linear-gradient(180deg, ${rgbaTriplet(tokens.colors.surfaceGlass, tokens.opacity.glassSoft)}, ${rgbaTriplet(tokens.colors.surface, tokens.opacity.glassLight)}), ${surfaceStyles.rainWash}`,
    "--glass-control-bg": rgbaTriplet(tokens.colors.surfaceGlass, tokens.opacity.glassLight),
    "--glass-chip-bg": rgbaTriplet(tokens.colors.surfaceGlass, tokens.opacity.glassLight),
    "--glass-chip-accent-bg": `linear-gradient(180deg, ${rgbaTriplet(tokens.akePalette.orange, "0.9")}, ${rgbaTriplet(tokens.akePalette.orangeDeep, "0.72")})`,
    "--glass-chip-active-bg": `linear-gradient(180deg, ${rgbaTriplet(tokens.colors.surfaceGlass, "0.88")}, ${rgbaTriplet(tokens.akePalette.mist, tokens.opacity.glassSoft)})`,
    "--glass-nav-bg": rgbaTriplet(tokens.colors.surfaceGlass, tokens.opacity.glassFaint),
    "--glass-media-bg": `radial-gradient(circle at top, ${rgbaTriplet(tokens.colors.surfaceGlass, "0.54")}, transparent 60%), linear-gradient(180deg, ${rgbaTriplet(tokens.akePalette.mist, "0.82")}, ${rgbaTriplet(tokens.colors.surfaceStrong, "0.62")})`,
    "--glass-icon-bg": rgbaTriplet(tokens.colors.surfaceGlass, tokens.opacity.tintSoft),
    "--glass-page-glow": surfaceStyles.pageGlow,
    "--glow-ake-halo": `radial-gradient(circle at center, ${rgbaTriplet(tokens.akePalette.orange, tokens.opacity.glowSoft)}, transparent 60%)`,
    "--glow-ake-ring": `0 0 32px ${rgbaTriplet(tokens.akePalette.orange, tokens.opacity.glowStrong)}`,
    "--layout-max-width": tokens.layout.maxWidth,
    "--workbench-columns": tokens.workbench.columns,
    "--workbench-panel-padding": tokens.workbench.panelPadding,
    "--workbench-panel-gap": tokens.workbench.panelGap,
    "--workbench-section-gap": tokens.workbench.sectionGap,
    "--workbench-input-surface": tokens.workbench.inputSurface,
    "--workbench-settings-surface": tokens.workbench.settingsSurface,
    "--workbench-output-surface": tokens.workbench.outputSurface,
    "--workbench-subpanel-surface": tokens.workbench.subpanelSurface,
    "--workbench-drawer-width": tokens.drawer.width,
    "--workbench-drawer-height": tokens.drawer.height,
    "--workbench-drawer-padding": tokens.drawer.padding,
    "--button-glass-primary": tokens.button.glassPrimary,
    "--button-glass-secondary": tokens.button.glassSecondary,
    "--button-glass-ghost": tokens.button.glassGhost,
    "--button-hover-glow": tokens.button.hoverGlow,
    "--surface-panel-tint": tokens.surface.panelTint,
    "--surface-panel-highlight": tokens.surface.panelHighlight,
    "--page-bg-base": background.base,
    "--page-bg-image": background.imageSrc ? `url("${background.imageSrc}")` : "none",
    "--page-bg-overlay": background.overlay,
    "--page-bg-blur": background.blur,
    "--page-bg-brightness": background.brightness,
  };
}
